name: Bright X
markdown: kramdown
highlighter: rouge

# Setup
title:               Bright X
description:         'Bright X is a pop-up creative newsroom producing video, photography and text to record and amplify defining moments of professional success.'
tagline:             A pop-up creative newsroom
url:                 https://www.brightx.media
logo:                /images/BrightX-Logo-ColourWhiteBack-01-web.png
tel:                 +971502206916
email:               ta@ashbright.com
calltoaction:        "Get in touch"
analytics:           106864288
address:
  name:              ASHBRIGHT DWC-LLC
  region:            Dubai
  postcode:          712472
  country:           UAE

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _pages

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /images/BrightX-Logo-ColourWhiteBack-01-web.png
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/
